### ISSUE TITLE
Couldn't find libkodein-leveldb-jni.so

### ISSUE THREAD

**Issue by arnis-shaykh** [Kodein-Framework/Kodein-DB#21]
I am trying to use KodeinDB in the multiplatform project. When I launch an android version it crashes when I call `DB.open()` with the following message:

`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/-Rxjf0bGn-KdI6RxnvdmLZQ==/base.apk"],nativeLibraryDirectories=[/data/app/-Rxjf0bGn-KdI6RxnvdmLZQ==/lib/arm64, /system/lib64, /product/lib64]]] couldn't find "libkodein-leveldb-jni.so"`

What can i do to fix this?

**Comment by CarsonRedeye** [comment]
I get something similar when trying to run on emulator
```
java.lang.ExceptionInInitializerError
        at org.kodein.db.impl.data.DataDBJvm.getLdbFactory(DataDBJvm.kt:10)
        at org.kodein.db.impl.data.AbstractDataDBFactory.open(AbstractDataDBFactory.kt:18)
        at org.kodein.db.impl.data.AbstractDataDBFactory.open(AbstractDataDBFactory.kt:11)
        at org.kodein.db.impl.model.AbstractModelDBFactory.open(AbstractModelDBFactory.kt:21)
        at org.kodein.db.impl.model.AbstractModelDBFactory.open(AbstractModelDBFactory.kt:9)
        at org.kodein.db.impl.AbstractDBFactory.open(AbstractDBFactory.kt:25)
        at org.kodein.db.impl.AbstractDBFactory.open(AbstractDBFactory.kt:10)
        at org.kodein.db.impl.DefaultKt.open(default.kt:7)
        at co.redeye.dms.application.MainActivity.test_nosql_insertion_speed(MainActivity.kt:87)
        at co.redeye.dms.application.MainActivity.onCreate(MainActivity.kt:83)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalStateException: Could not load kodein-leveldb-jni-linux. Have you added it to the classpath?
        at org.kodein.db.leveldb.jvm.LevelDBJvm.<clinit>(LevelDBJvm.kt:25)
        at org.kodein.db.impl.data.DataDBJvm.getLdbFactory(DataDBJvm.kt:10) 
        at org.kodein.db.impl.data.AbstractDataDBFactory.open(AbstractDataDBFactory.kt:18) 
        at org.kodein.db.impl.data.AbstractDataDBFactory.open(AbstractDataDBFactory.kt:11) 
        at org.kodein.db.impl.model.AbstractModelDBFactory.open(AbstractModelDBFactory.kt:21) 
        at org.kodein.db.impl.model.AbstractModelDBFactory.open(AbstractModelDBFactory.kt:9) 
        at org.kodein.db.impl.AbstractDBFactory.open(AbstractDBFactory.kt:25) 
        at org.kodein.db.impl.AbstractDBFactory.open(AbstractDBFactory.kt:10) 
        at org.kodein.db.impl.DefaultKt.open(default.kt:7) 
        at co.redeye.dms.application.MainActivity.test_nosql_insertion_speed(MainActivity.kt:87) 
        at co.redeye.dms.application.MainActivity.onCreate(MainActivity.kt:83) 
        at android.app.Activity.performCreate(Activity.java:7009) 
        at android.app.Activity.performCreate(Activity.java:7000) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: java.lang.ClassNotFoundException: org.kodein.db.leveldb.jvm.LevelDBJvmLinuxLoader
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at org.kodein.db.leveldb.jvm.LevelDBJvm.<clinit>(LevelDBJvm.kt:20)
        at org.kodein.db.impl.data.DataDBJvm.getLdbFactory(DataDBJvm.kt:10) 
        at org.kodein.db.impl.data.AbstractDataDBFactory.open(AbstractDataDBFactory.kt:18) 
        at org.kodein.db.impl.data.AbstractDataDBFactory.open(AbstractDataDBFactory.kt:11) 
        at org.kodein.db.impl.model.AbstractModelDBFactory.open(AbstractModelDBFactory.kt:21) 
        at org.kodein.db.impl.model.AbstractModelDBFactory.open(AbstractModelDBFactory.kt:9) 
        at org.kodein.db.impl.AbstractDBFactory.open(AbstractDBFactory.kt:25) 
        at org.kodein.db.impl.AbstractDBFactory.open(AbstractDBFactory.kt:10) 
        at org.kodein.db.impl.DefaultKt.open(default.kt:7) 
        at co.redeye.dms.application.MainActivity.test_nosql_insertion_speed(MainActivity.kt:87) 
        at co.redeye.dms.application.MainActivity.onCreate(MainActivity.kt:83) 
        at android.app.Activity.performCreate(Activity.java:7009) 
        at android.app.Activity.performCreate(Activity.java:7000) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.kodein.db.leveldb.jvm.LevelDBJvmLinuxLoader" on path: DexPathList[[zip file "/data/app/co.redeye.dms.dev-HqxpfzTPl4M1MTVNQgnhfA==/base.apk"],nativeLibraryDirectories=[/data/app/co.redeye.dms.dev-HqxpfzTPl4M1MTVNQgnhfA==/lib/x86, /data/app/co.redeye.dms.dev-HqxpfzTPl4M1MTVNQgnhfA==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        
```

**Comment by SalomonBrys** [comment]
Version [`0.5.0`](https://github.com/Kodein-Framework/Kodein-DB/releases/tag/0.5.0-beta) fixes the issue.

Sorry about that.
