### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/kodein/db/leveldb/jvm/LevelDBJvm;

### ISSUE THREAD

**Issue by CarsonRedeye** [Kodein-Framework/Kodein-DB#22]
When trying to run instrumented test on android.
trying to test performance via android benchmarking but can't run test:
```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/kodein/db/leveldb/jvm/LevelDBJvm;
	at org.kodein.db.impl.data.DataDBJvm.getLdbFactory(DataDBJvm.kt:10)
	at org.kodein.db.impl.data.AbstractDataDBFactory.open(AbstractDataDBFactory.kt:18)
	at org.kodein.db.impl.data.AbstractDataDBFactory.open(AbstractDataDBFactory.kt:11)
	at org.kodein.db.impl.model.AbstractModelDBFactory.open(AbstractModelDBFactory.kt:21)
	at org.kodein.db.impl.model.AbstractModelDBFactory.open(AbstractModelDBFactory.kt:9)
	at org.kodein.db.impl.AbstractDBFactory.open(AbstractDBFactory.kt:25)
	at org.kodein.db.impl.AbstractDBFactory.open(AbstractDBFactory.kt:10)
	at org.kodein.db.impl.DefaultKt.open(default.kt:7)
```

**Comment by CarsonRedeye** [comment]
Same thing happens when i try to run on device. API 30, Gradle 6.7, AS 4.2 canary 15

**Comment by romainbsl** [comment]
Can you share your gradle configuration ? It seems you are missing some part of the API.

**Comment by CarsonRedeye** [comment]
```
maven {
            url 'https://dl.bintray.com/kodein-framework/Kodein-DB'
        }
```

build.gradle(:app)
```

    implementation "org.kodein.db:kodein-db-jvm:0.4.0-beta"
    implementation("org.kodein.db:kodein-db-serializer-kotlinx:0.4.0-beta")
```
I'm not sure what else is relevant

**Comment by CarsonRedeye** [comment]
I just tried adding it to a different android project and get a different crash 
```
 Caused by: java.lang.ClassNotFoundException: Didn't find class "org.kodein.db.leveldb.jvm.LevelDBJvmLinuxLoader" on path: DexPathList
```
Can you add a working android example to the repo?

**Comment by CarsonRedeye** [comment]
I get the same error creating a fresh new android project with AS 4.2 and just adding these dependencies
```
        maven { url = "https://dl.bintray.com/kodein-framework/Kodein-DB" }
```
```
    implementation("org.kodein.db:kodein-db-jvm:0.4.0-beta")
    implementation("org.kodein.db:kodein-db-serializer-kryo-jvm:0.4.0-beta")
```
and calling 
```
            val db = DB.inDir(applicationContext.filesDir.absolutePath).open("TEST_DB_NO_SQL")
```

**Comment by CarsonRedeye** [comment]
Full gradle scripts:
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = "1.4.10"
    repositories {
        google()
        jcenter()
        maven { url = "https://dl.bintray.com/kodein-framework/Kodein-DB" }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.1.1"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
```
plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.2"

    defaultConfig {
        applicationId "com.example.testkodeindb"
        minSdkVersion 23
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation "org.kodein.db:kodein-db-jvm:0.4.0-beta"
    implementation "org.kodein.db:kodein-db-serializer-kryo-jvm:0.4.0-beta"

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.3.1'
    implementation 'androidx.navigation:navigation-ui-ktx:2.3.1'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}
```

**Comment by CarlosEsco** [comment]
fyi: I was having similar issues and tried to downgrade to 0.3.0-beta and it didn't fix either

**Comment by romainbsl** [comment]
your repo declaration is wrong. You should put `maven { url = "https://dl.bintray.com/kodein-framework/Kodein-DB" }` in `allprojects.repositories`

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url = "https://dl.bintray.com/kodein-framework/Kodein-DB" }
    }
}
```

**Comment by CarlosEsco** [comment]
mine is in the allprojects and it doesnt change anything

java.lang.NoClassDefFoundError: Failed resolution of: Lorg/kodein/db/leveldb/jvm/LevelDBJvm
```
org.kodein.db:kodein-db-jvm
org.kodein.db:kodein-db-serializer-kotlinx
```

are the two i am using

**Comment by CarsonRedeye** [comment]
Agree that doesn't fix it for me. Is it something to do with using in a pure android project, not a multiplatform one?

**Comment by romainbsl** [comment]
I just reproduced your issue, I will investigate.
This should be usable from a JVM project as well as for multiplatform.

**Comment by romainbsl** [comment]
In fact, if you are using **Gradle 6+** you don't need to specify the target for `kodein-db` dependencies.

something like this should work:
```
org.kodein.db:kodein-db:0.4.0-beta
org.kodein.db:kodein-db-serializer-kotlinx:0.4.0-beta
```

**Comment by CarsonRedeye** [comment]
OK great that fixed the issue, but now I get this crash https://github.com/Kodein-Framework/Kodein-DB/issues/21

**Comment by romainbsl** [comment]
On it.
