### ISSUE TITLE
Custom types for models crashing

### ISSUE THREAD

**Issue by RadmirOne** [Kodein-Framework/Kodein-DB#29]
I have model for Kotlin Multiplatform with custom type `DateTime`
```
@Serializable
data class StoryEntity(
    override val id: Long,
    val text: String,
    @Serializable(with = DateTimeSerializer::class)
    val startDate: DateTime?,
) : Metadata
```
and KSerializer
```
object DateTimeSerializer : KSerializer<DateTime> {

    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor(
        DateTime::class.platformSimpleName,
        PrimitiveKind.LONG
    )

    override fun deserialize(decoder: Decoder): DateTime = DateTime.fromUnix(decoder.decodeLong())

    override fun serialize(encoder: Encoder, value: DateTime) = encoder.encodeLong(value.unixMillisLong)
}
```
db open
```
val db = DB.open(
                DBPathPlatform.dbPath(),
                ModelCache.Disable,
                KotlinxSerializer {
                    +StoryEntity.serializer()
                }
            )
```
And I get an exception when I try to get the data 
```
java.lang.IllegalAccessError: Method 'void com.example.stories.models.StoryEntity.<init>(int, long, java.lang.String, com.soywiz.klock.DateTime, kotlinx.serialization.internal.SerializationConstructorMarker)' is inaccessible to class 'com.example.stories.models.StoryEntity$$serializer' (declaration of 'com.example.stories.models.StoryEntity$$serializer' appears in /data/app/com.example.client.prerelease-1/base.apk:classes4.dex)
        at com.example.stories.models.StoryEntity$$serializer.deserialize(StoryEntity.kt)
        at com.example.stories.models.StoryEntity$$serializer.deserialize(StoryEntity.kt:9)
        at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:257)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:17)
        at kotlinx.serialization.cbor.internal.CborReader.decodeSerializableValue(Encoding.kt:282)
        at kotlinx.serialization.cbor.Cbor.decodeFromByteArray(Cbor.kt:53)
        at org.kodein.db.orm.kotlinx.KotlinxSerializer.deserialize(KotlinxSerializer.kt:85)
        at org.kodein.db.impl.model.ModelDBImpl.deserialize$kodein_db_debug(ModelDBImpl.kt:143)
        at org.kodein.db.impl.model.ModelReadModule$DefaultImpls.get(ModelReadModule.kt:19)
        at org.kodein.db.impl.model.ModelDBImpl.get(ModelDBImpl.kt:18)
        at org.kodein.db.impl.DBReadModule$DefaultImpls.get(DBReadModule.kt:12)
        at org.kodein.db.impl.DBImpl.get(DBImpl.kt:9)
```
if i remove the custom type it works well

**Comment by SalomonBrys** [comment]
This looks like a KotlinX.Serializer issue.
