### ISSUE TITLE
Compilation failed: Backend Internal error: Exception during IR lowering

### ISSUE THREAD

**Issue by jliu82** [Kodein-Framework/Kodein-DB#34]
I'm not able to compile the multiplatform project with version 0.8.0-beta because of this error: 
```
Task :shared:linkDebugFrameworkIos
e: Compilation failed: Backend Internal error: Exception during IR lowering
File being compiled: /Users/runner/work/Kodein-DB/Kodein-DB/ldb/kodein-leveldb-inmemory/src/commonMain/kotlin/org/kodein/db/leveldb/inmemory/InMemoryLevelDB.kt
The root cause java.lang.AssertionError was thrown at: org.jetbrains.kotlin.ir.overrides.FakeOverrideBuilderStrategy.fakeOverrideMember(IrOverridingUtil.kt:43)

 * Source files: 
 * Compiler version info: Konan: 1.4.30 / Kotlin: 1.4.30
 * Output kind: STATIC_CACHE

e: org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during IR lowering
File being compiled: /Users/runner/work/Kodein-DB/Kodein-DB/ldb/kodein-leveldb-inmemory/src/commonMain/kotlin/org/kodein/db/leveldb/inmemory/InMemoryLevelDB.kt
e: Compilation failed: Backend Internal error: Exception during IR lowering

The root cause java.lang.AssertionError was thrown at: org.jetbrains.kotlin.ir.overrides.FakeOverrideBuilderStrategy.fakeOverrideMember(IrOverridingUtil.kt:43)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException(CodegenUtil.kt:239)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException$default(CodegenUtil.kt:235)
	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invoke(PhaseBuilders.kt:124)
	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invoke(PhaseBuilders.kt:112)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:94)
	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:30)

e: org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during IR lowering

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.AssertionError: Unexpected variance in super type argument: in @0
	at org.jetbrains.kotlin.ir.overrides.FakeOverrideBuilderStrategy.fakeOverrideMember(IrOverridingUtil.kt:43)
	at org.jetbrains.kotlin.ir.overrides.IrOverridingUtil.buildFakeOverridesForClassUsingOverriddenSymbols(IrOverridingUtil.kt:168)
	at org.jetbrains.kotlin.backend.common.ir.IrUtilsKt.addFakeOverrides(IrUtils.kt:487)
	at org.jetbrains.kotlin.backend.common.ir.IrUtilsKt.addFakeOverrides$default(IrUtils.kt:485)
	at org.jetbrains.kotlin.backend.konan.lower.FunctionReferenceLowering$FunctionReferenceBuilder.build(FunctionReferenceLowering.kt:335)

Caused by: java.lang.AssertionError: Unexpected variance in super type argument: in @0

	at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
	at org.jetbrains.kotlin.ir.expressions.IrContainerExpression.transformChildren(IrBlock.kt:41)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitExpression(IrElementTransformerVoid.kt:131)
	at org.jetbrains.kotlin.backend.konan.lower.FunctionReferenceLowering$lower$1.visitExpression(FunctionReferenceLowering.kt:67)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitContainerExpression(IrElementTransformerVoid.kt:150)
```

I have :
org.kodein.db:kodein-db:0.8.0-beta in commonMain
org.kodein.db:kodein-db-inmemory:0.8.0-beta in commonTest

**Comment by romainbsl** [comment]
This was an issue in Kotlin compiler, fixed in `1.4.31` https://youtrack.jetbrains.com/issue/KT-44826

However, Kodein-DB `0.8.0-beta` and `0.8.1-beta` are based on Kotlin 1.5, you might consider upgrading your project :)
